"""Initial migration

Revision ID: 04440dcecb17
Revises: 
Create Date: 2026-01-28 13:25:49.678036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04440dcecb17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('evidence_refs', sa.Text(), nullable=True),
    sa.Column('costs', sa.Float(), nullable=True),
    sa.Column('parties', sa.Text(), nullable=True),
    sa.Column('audit', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('closure_code', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_case_number'), ['case_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_cases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=255), nullable=False),
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('assets', sa.Text(), nullable=True),
    sa.Column('stakeholders', sa.Text(), nullable=True),
    sa.Column('laycan_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('laycan_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movements_status'), ['status'], unique=False)

    op.create_table('playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('required_roles', sa.Text(), nullable=True),
    sa.Column('escalation_rules', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playbooks_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_playbooks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playbooks_incident_type'), ['incident_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_movement_id'), ['movement_id'], unique=False)

    op.create_table('evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('file_ref', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('evidence_metadata', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('blockchain_hash', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidences_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidences_id'), ['id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_critical_alerts', sa.Boolean(), nullable=True),
    sa.Column('email_high_alerts', sa.Boolean(), nullable=True),
    sa.Column('email_medium_alerts', sa.Boolean(), nullable=True),
    sa.Column('email_low_alerts', sa.Boolean(), nullable=True),
    sa.Column('email_case_updates', sa.Boolean(), nullable=True),
    sa.Column('email_daily_digest', sa.Boolean(), nullable=True),
    sa.Column('websocket_enabled', sa.Boolean(), nullable=True),
    sa.Column('websocket_sound', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sla_timer', sa.Integer(), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('site_zone', sa.String(length=100), nullable=True),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_domain'))

    op.drop_table('alerts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_id'))

    op.drop_table('notification_preferences')
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidences_id'))
        batch_op.drop_index(batch_op.f('ix_evidences_case_id'))

    op.drop_table('evidences')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_movement_id'))
        batch_op.drop_index(batch_op.f('ix_events_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))

    op.drop_table('events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playbooks_incident_type'))
        batch_op.drop_index(batch_op.f('ix_playbooks_id'))
        batch_op.drop_index(batch_op.f('ix_playbooks_domain'))

    op.drop_table('playbooks')
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movements_status'))
        batch_op.drop_index(batch_op.f('ix_movements_id'))

    op.drop_table('movements')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_priority'))
        batch_op.drop_index(batch_op.f('ix_cases_id'))
        batch_op.drop_index(batch_op.f('ix_cases_case_number'))

    op.drop_table('cases')
    # ### end Alembic commands ###
